#!/usr/bin/env php
<?php

define('DEBUG', true);

if(DEBUG)
{
    error_reporting(-1);

} else {
    error_reporting(0);
}

main($argc, $argv);

function main($argc, $argv)
{
    if ( $argc < 2 || in_array($argv[1], array('--help', '-help', '-h', '-?'))) {
        help();
        exit();
    }
    
    unset($argv[0]);
    
    foreach($argv as $curso)
    {
        
    }
}


function help()
{
$help = <<<EOT
Uso: emec_crawler (CURSO [...])
Exemplo: emec_crawler enfermagem psicologia

EOT;

    echo $help;
}
