#!/usr/bin/env php
<?php

require_once('./utils.php');

main($argc, $argv);

function main($argc, $argv)
{
    if ( $argc < 2 || in_array($argv[1], array('--help', '-help', '-h', '-?'))) {
        help();
        exit();
    }
    
    $pagina = curl($argv[1]);
    echo $pagina;
}

function help()
{
    //TODO
}
