#!/usr/bin/env php
<?php

define('DEBUG', true);

if(DEBUG)
{
    error_reporting(-1);

} else {
    error_reporting(0);
}

// verifica os parâmetros
if ( $argc < 2 || in_array($argv[1], array('--help', '-help', '-h', '-?'))) {
    help();
}

function help()
{
$help = <<<EOT
Uso: emec_crawler (CURSO [...])
Exemplo: emec_crawler enfermagem psicologia

EOT;

    echo $help;
}
